Repository humorie/Humorie-Frontend, pull requests merged in 2024-08, with the labels that each got.

#62 [Feat] 메인페이지 API 기능구현
  src/assets/images/icon/icon_start_pink.svg
  src/components/main/CardRecommend.tsx
  src/components/main/CardReview.tsx
  src/components/main/CardReview1.tsx
  src/components/main/CardReview2.tsx
  src/components/main/Category.tsx
  src/components/main/Contents.tsx
  src/components/main/Rending.tsx
  src/index.css
  src/store/store.tsx
  vite.config.ts
Labels: 기능 구현, 퍼블리싱

#65 [Feat] 상담내역 API 기능구현
  src/assets/images/icon/icon_arrow_right_white.svg
  src/components/counseling/dropdownGender.tsx
  src/components/counseling/dropdownMethod.tsx
  src/components/counseling/dropdownRegion.tsx
  src/components/counseling/dropdownViews.tsx
  src/components/header/Header.tsx
  src/components/history/Contents.tsx
  src/components/history/EmptyPost.tsx
  src/components/history/GoToLogin.tsx
  src/components/history/Posts.tsx
  src/pages/History.tsx
  src/store/store.tsx
Labels: 기능 구현, 퍼블리싱

#67 [Feat] 상담 페이지 API 연동
  src/App.tsx
  src/components/counseling/Modal/searchmodal.tsx
  src/components/counseling/counselorcard.tsx
  src/components/counseling/counselorlist.tsx
  src/components/counseling/dropdownGender.tsx
  src/components/counseling/dropdownMethod.tsx
  src/components/counseling/dropdownRegion.tsx
  src/components/counseling/dropdownViews.tsx
  src/components/counselor/career.tsx
  src/components/counselor/introduction.tsx
  src/components/counselor/profile.tsx
  src/components/counselor/review.tsx
  src/components/counselor/reviewcard.tsx
  src/components/header/Header.tsx
  src/components/main/Rending.tsx
  src/store/store.tsx
Labels: 기능 구현

#69 [feat] 상담하기 태그 기능 & 리뷰 상세 페이지 API 적용
  src/App.tsx
  src/components/counseling/counselorcard.tsx
  src/components/counseling/findcounselor.tsx
  src/components/counselor/review.tsx
  src/components/counselor/reviews/reviews_reviewcard_all.tsx
  src/components/counselor/reviews/reviews_reviews_all.tsx
  src/pages/Counselor.tsx
  src/pages/Reviews.tsx
Labels: 기능 구현

#79 [Design] 고객센터 디자인 및 기능추가, 다른 페이지들 일부 수
  src/App.tsx
  src/assets/images/customerService/cs_rending_image1.svg
  src/assets/images/icon/icon_eye_gray.svg
  src/assets/images/icon/icon_list_gray.svg
  src/assets/images/icon/icon_person_gray.svg
  src/assets/images/icon/icon_time_gray.svg
  src/components/Pagenation.tsx
  src/components/Tag.tsx
  src/components/Types.tsx
  src/components/cs/list.tsx
  src/components/customerService/list.tsx
  src/components/customerService/search.tsx
  src/components/history/Contents.tsx
  src/components/history/Posts.tsx
  src/components/history/RecentPost.tsx
  src/components/history/post/Contents.tsx
  src/components/history/post/Details.tsx
  src/components/history/post/Profile.tsx
  src/components/main/CardRecommend.tsx
  src/components/main/Category.tsx
  src/components/main/Notice.tsx
  src/components/notice_post/Contents.tsx
  src/components/notice_post/Rending.tsx
  src/components/review/MyTagModal.tsx
  src/pages/Complete.tsx
  src/pages/CustomerService.tsx
  src/pages/CustomerServicePost.tsx
  src/pages/NoticePost.tsx
  src/pages/Review.tsx
  src/store/store.tsx
Labels: 기능 구현, 퍼블리싱

#83 [Refactor] 데모준비 디자인 및 기능 수정
  src/App.tsx
  src/assets/images/info/info_rending_image1.svg
  src/assets/images/info/info_rending_image2.svg
  src/components/Pagenation.tsx
  src/components/ScrollToTop.tsx
  src/components/counselor/profile.tsx
  src/components/customerService/Banner.tsx
  src/components/customerService/list.tsx
  src/components/customerService/search.tsx
  src/components/history/Contents.tsx
  src/components/history/RecentPost.tsx
  src/components/history/post/Contents.tsx
  src/components/info/Location.tsx
  src/components/info/Rending.tsx
  src/components/info/ServiceHistory.tsx
  src/components/login/LoginForm.tsx
  src/components/main/CardRecommend.tsx
  src/components/main/CardReview.tsx
  src/components/main/Category.tsx
  src/components/reservation/CardReservation.tsx
  src/pages/CustomerService.tsx
  src/pages/CustomerServicePost.tsx
  src/services/read.tsx
Labels: 리팩토링
